name: Tests and Coverage
on:
  - push
  - pull_request
jobs:
  test:
    name: Test and Build
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make
        run: make update && make correct

      - name: Test
        run: go test -v . -race

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make
        run: make update && make correct

      - name: Generage coverage
        run: go test -v . -coverprofile=coverage.txt -covermode=atomic

      - name: Publish coverage
        uses: codecov/codecov-action@v5
